[build]
target-dir = "target"

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+bulk-memory,+mutable-globals"]

[alias]
build-wasm32 = "build --target wasm32-unknown-unknown --release"
